### ISSUE TITLE
container not starting, TypeError: Cannot call method 'split' of undefined

### ISSUE THREAD

**Issue by mimizone** [ekristen/docker-index#16]
Hi, I cloned the docker-index repo, built the image successfully, but when attempting to run the container, I got the following errors multiple times.

```
Error: Cannot parse config file: '/opt/app/config/docker.js': TypeError: Cannot call method 'split' of undefined
    at Config._parseFile (/opt/app/node_modules/config/lib/config.js:949:11)
    at /opt/app/node_modules/config/lib/config.js:718:25
    at Array.forEach (native)
    at /opt/app/node_modules/config/lib/config.js:714:14
    at Array.forEach (native)
    at Config._loadFileConfigs (/opt/app/node_modules/config/lib/config.js:713:13)
    at new Config (/opt/app/node_modules/config/lib/config.js:118:5)
    at Object.<anonymous> (/opt/app/node_modules/config/lib/config.js:1402:64)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

/opt/app/node_modules/config/lib/config.js:949
    throw new Error("Cannot parse config file: '" + fullFilename + "': " + e3)
```

I am not familiar with Node.js. Can you help me to find the problem?

**Comment by ekristen** [comment]
How are you trying to start the container?

**Comment by ekristen** [comment]
At a minimum you need to set the following environment variables using the docker run command

```
REGISTRIES=registry.private.io
```

**Comment by mimizone** [comment]
thanks. I had forgotten to check the docker.js file....
I finally got stuff working using a modified version of the fig.yml file you provided to use my own containers.
thanks a lot!

**Comment by ekristen** [comment]
Fantastic. Glad its working. I welcome any feedback you might have about it.
