### ISSUE TITLE
self signed ssl issue in python

### ISSUE THREAD

**Issue by mimizone** [ekristen/docker-index#17]
I deployed a full registry stack using the fig.yml file, with just a slightly custom modified registry.

I can authenticate to docker with the generated index admin/password.
When pushing an image to the admin repository, I get SSL error because the CA is not trusted.

my certificates are self signed.
I added the CA certificate in /usr/local/share/ca-certificates/ and ran update-ca-certificates
but still get the same error.

are you familiar with this issue?

```
registry_1 | 12/Feb/2015:06:33:40 +0000 ERROR: Exception on /v1/images/511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158/json [PUT]
registry_1 | Traceback (most recent call last):
registry_1 |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
registry_1 |     response = self.full_dispatch_request()
registry_1 |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
registry_1 |     rv = self.handle_user_exception(e)
registry_1 |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
registry_1 |     reraise(exc_type, exc_value, tb)
registry_1 |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
registry_1 |     rv = self.dispatch_request()
registry_1 |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
registry_1 |     return self.view_functions[rule.endpoint](**req.view_args)
registry_1 |   File "/usr/local/lib/python2.7/dist-packages/docker_registry/toolkit.py", line 279, in wrapper
registry_1 |     if check_signature() is True or check_token(kwargs) is True:
registry_1 |   File "/usr/local/lib/python2.7/dist-packages/docker_registry/toolkit.py", line 231, in check_token
registry_1 |     if validate_token(auth) is False:
registry_1 |   File "/usr/local/lib/python2.7/dist-packages/docker_registry/toolkit.py", line 159, in validate_token
registry_1 |     resp = requests.get(url, verify=True, headers=headers)
registry_1 |   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 55, in get
registry_1 |     return request('get', url, **kwargs)
registry_1 |   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 44, in request
registry_1 |     return session.request(method=method, url=url, **kwargs)
registry_1 |   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 456, in request
registry_1 |     resp = self.send(prep, **send_kwargs)
registry_1 |   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 559, in send
registry_1 |     r = adapter.send(request, **kwargs)
registry_1 |   File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 382, in send
registry_1 |     raise SSLError(e, request=request)
registry_1 | SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

**Comment by ekristen** [comment]
If you take a look at 

* https://github.com/ekristen/docker-index-registry
* https://github.com/ekristen/docker-index-nginx

Those are setup to inject the SSL certificates properly, you can fork them and replace the SSL with your own.

**Comment by mimizone** [comment]
Thanks again. I would prefer to have python use the OS/ubuntu level certificates in /etc/ssl, but it is a perfect work around.
